name: lexs
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  firebase_auth: ^4.5.0
  firebase_core: ^2.0.0
  url_launcher: ^6.0.9

flutter:
  assets:
    - assets/3.jpg
    - assets/4.jpg
    - assets/5.jpg
    - assets/c.jpg
    - assets/7.jpeg
    - assets/8.jpeg
    - assets/12.png
    - assets/15.png
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
